# Site settings
title: Nitin Prakash
description: "Whatsup ya'll?"
url: "www.thenitinprakash.com"



# Secondary Parameters
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
baseurl: "https://thenitinprakash.com"
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"

# links
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact

#Social media links
twitter_username: Nitin63Nitin
facebook_username: AvengedEndie
github_username: nitinprakash96


# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"

# Prose Settings
prose:
  ignore: ['feed.xml', '/stl', '/ply', '/js', '/plugin', '/lib', '/projectors', '_layouts', '/_includes', 'Gruntfile.js', 'package.json', 'proselinks.jsonp', 'ppanchor.matin', '.gitignore', '/search', '/css', '/img', 'favicon.png','_data/*.json','LICENSES.md','README.md','colorscheme.scss','members.html','mentions.html','index.html']
  siteurl: 'www.thenitinprakash.com'
  ispp: true
  media: 'img'
  metadata:
    _posts:
      - name: "subtitle"
        field:
          element: "text"
          label: "Sub-Title (Short Description)"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Choose Layout"
          placeholder: "Layouts"
          options:
            - name: "Post"
              value: "post"
            - name: "Notebook"
              value: "notebook"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags (seperate with whitespace)"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Project"
          value: ""

      - name: "vertical"
        field:
          element: "hidden"
          value: </section><section markdown="1">

      - name: "theme"
        field:
          element: "select"
          label: "Theme (Slide)"
          placeholder: "Theme (Slide)"
          options:
            - name: "Beige"
              value: "beige"
            - name: "Blood"
              value: "blood"
            - name: "Moon"
              value: "moon"
            - name: "Night"
              value: "night"
            - name: "Sky"
              value: "sky"
            - name: "Solarized"
              value: "solarized"
      - name: "trans"
        field:
          element: "select"
          label: "Transition (Slide)"
          placeholder: "Transition (Slide)"
          options:
            - name: "Cube"
              value: "cube"
            - name: "Page"
              value: "page"
            - name: "Concave"
              value: "concave"
            - name: "Linear"
              value: "linear"
            - name: "Fade"
              value: "fade"
            - name: "None"
              value: "none"
