# Site settings
title:       Nitin Prakash
email:       prakash.nitin63@gmail.com
author:      Nitin Prakash
description: "A place where I store my thoughts"
baseurl:     ""
url:         "http://www.thenitinprakash.com"
date_format: "%b %-d, %Y"
header_pages:
 - about.md

 # Google analytics
google_analytics: "UA-120923664-1"


# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:


# Social icons
github_username: nitinprakash96
twitter_username: nitinprakash96
paypal_url: nitinprakash96

# Post sharing icons
show_social_icons: true
# Change to 'true' to enable individual icons
share_twitter: true
share_linkedin: false
share_reddit: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
